language: java
sudo: required

services:
  - docker

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "iosrmockservices" -p "Wojtek_1234";
    docker push discovery-service;
    fi