zuul:
  ribbonIsolationStrategy: THREAD
  eureka:
    integral-service:
      semaphore:
        maxSemaphores: 100
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis:  100000
  routes:
    kibana:
      path: /kibana/**
      url: http://kibana:5601/
      stripPrefix: true
    kibana-app:
      path: /app/kibana/**
      url: http://kibana:5601/
      stripPrefix: false
    zipkin:
      path: /zipkin/**
      serviceId: ZIPKIN
      stripPrefix: false
    service-dicovery:
      path: /discovery/**
      url: http://service-discovery:8761/
      stripPrefix: true
    service-dicovery-static:
      path: /eureka/**
      url: http://service-discovery:8761/
      stripPrefix: false

eureka:
  integral-service:
    semaphore:
      maxSemaphores: 100
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
    instance:
      leaseRenewalIntervalInSeconds: 5
      preferIpAddress: true

management:
  security:
    enabled: false

spring:
  application:
    name: zuul
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 120000
            
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000